In [1]:
import numpy as np

In [5]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
array = np.repeat([1.0, 2.0], 10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [13]:
array = np.repeat([1.0, 2.0], [5, 7])
array

array([1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.])

In [14]:
el = array[0]
el

1.0

In [15]:
el = array[5]
el

2.0

In [16]:
el = array[4]
el

1.0

In [19]:
print(array[[2, 4, 6, 8, 10]])

[1. 1. 2. 2. 2.]


In [20]:
array[0] = 7
array

array([7., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.])

In [21]:
elements = [1, 2,3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(array)

numpy.ndarray

In [24]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [27]:
zeros[0] = 300
zeros

C:\Users\vasir\AppData\Local\Temp\ipykernel_2520\1640675828.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [28]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [30]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [31]:
zeros.shape

(5, 2)

In [32]:
numbers = [                    
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numbers = np.array(numbers)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
array.shape

(4,)

In [34]:
numbers.shape

(3, 3)

In [35]:
numbers[1,1]

5

In [36]:
numbers[1, 1] = 77
numbers

array([[ 1,  2,  3],
       [ 4, 77,  6],
       [ 7,  8,  9]])

In [37]:
numbers[0]

array([1, 2, 3])

In [38]:
numbers[:, 3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [39]:
numbers[:, 2]

array([3, 6, 9])

In [41]:
numbers[0] = [1, 1, 1]
numbers

array([[ 1,  1,  1],
       [ 4, 77,  6],
       [ 7,  8,  9]])

In [42]:
numbers[:, 1] = [77, 77, 77]
numbers

array([[ 1, 77,  1],
       [ 4, 77,  6],
       [ 7, 77,  9]])

In [44]:
array = np.random
array

<module 'numpy.random' from 'C:\\Users\\vasir\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [45]:
array = np.random.rand(5, 2)
array

array([[0.30870435, 0.18003339],
       [0.70236696, 0.25526627],
       [0.84557616, 0.41976517],
       [0.72806321, 0.43901063],
       [0.73421183, 0.00939059]])

In [46]:
np.random.seed(2)

In [57]:
np.random.seed(2)
array = np.random.rand(7, 2)
array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728],
       [0.62113383, 0.52914209],
       [0.13457995, 0.51357812]])

In [58]:
array = np.random.randn(5, 2)
array

array([[ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525],
       [-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905]])

In [59]:
array = np.random.rand(5, 2)
array

array([[0.226012  , 0.10694568],
       [0.22030621, 0.34982629],
       [0.46778748, 0.20174323],
       [0.64040673, 0.48306984],
       [0.50523672, 0.38689265]])

In [62]:
np.random.seed(2)
array = np.random.randint(low=0, high=100, size=(5, 2))
array

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [67]:
np.random.seed(2)
array = np.random.rand(5, 2)
array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [70]:
idx = np.arange(5)
print("before shuffle", idx)
np.random.shuffle(idx)
print("after shuffle", idx)

before shuffle [0 1 2 3 4]
after shuffle [3 2 1 0 4]


In [3]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [4]:
array * 2

array([0, 2, 4, 6, 8])

In [18]:
np.random.seed(2)
v1 = np.random.randint(low=1, high=10, size=(4))
v2 = np.random.randint(low=1, high=10, size=(4))
print(v1)
print(v2)

[9 9 7 3]
[9 8 3 2]


In [19]:
print(v1.dot(v2))

180
